# Generated by Django 4.2.7 on 2023-12-03 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Service.service')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
            },
            bases=('Service.service',),
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('servicerecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Service.servicerecord')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccinations Records',
            },
            bases=('Service.servicerecord',),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_date', models.DateField(verbose_name='Campaign Date')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='Vaccination.vaccination', verbose_name='Vaccination')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
    ]
