# Generated by Django 4.2.7 on 2023-12-03 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('attending_time', models.DateTimeField(verbose_name='Attending Time')),
                ('leaving_time', models.DateTimeField(verbose_name='Leaving Time')),
            ],
            options={
                'verbose_name': 'Laboratory Attendance',
                'verbose_name_plural': 'Laboratory Attendances',
            },
        ),
        migrations.CreateModel(
            name='Bonuss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Bonuss',
                'verbose_name_plural': 'Bonusss',
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deduction Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
            },
        ),
    ]
