# Generated by Django 4.2.7 on 2023-12-03 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salary', models.FloatField(blank=True, null=True, verbose_name='Salary')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'permissions': [('set_published_status', 'Can set the status of the post to either publish or not')],
            },
            bases=('User.user',),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_date', models.DateField(verbose_name='Vacation Date')),
                ('is_accepted', models.BooleanField(default=True, verbose_name='is Accepted')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is Paid')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vacations', to='Employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Vacation',
                'verbose_name_plural': 'Vacations',
            },
        ),
        migrations.AddField(
            model_name='deduction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Deductions', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='bonuss',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attendances', to='Employee.employee', verbose_name='Employee'),
        ),
    ]
