# Generated by Django 4.2.7 on 2023-12-03 15:53

import Utils.Custom_Fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('User', '0001_initial'),
        ('VitalSign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('bar_code', Utils.Custom_Fields.BarCodeField(max_length=24, primary_key=True, serialize=False, verbose_name='BarCode')),
                ('diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visits', to='Doctor.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visits', to='User.profile', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
        ),
        migrations.CreateModel(
            name='VisitVitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(verbose_name='Result')),
                ('neg_or_pos', models.CharField(blank=True, choices=[('N', 'Negative'), ('VP', 'Very Weak Positive'), ('WP', 'Weak Positive'), ('P', 'Positive'), ('SP', 'Strong Positive')], max_length=2, null=True, verbose_name='Description(Positive/Negative)')),
                ('description_level', models.CharField(choices=[('L', 'Low'), ('N', 'Normal'), ('H', 'High')], max_length=1, verbose_name='Description Level')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Visit_Vital_Signs', to='Visit.visit', verbose_name='Visit')),
                ('vital_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prescriptions', to='VitalSign.vitalsign', verbose_name='Vital Sign')),
            ],
            options={
                'verbose_name': 'Visit Vital Sign',
                'verbose_name_plural': 'Visit Vital Signs',
                'unique_together': {('visit', 'vital_sign')},
            },
        ),
    ]
