# Generated by Django 4.2.7 on 2023-12-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Service.service')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Symbol')),
                ('min_normal', models.FloatField(blank=True, null=True, verbose_name='Minmum Normal Value')),
                ('max_normal', models.FloatField(blank=True, null=True, verbose_name='Maximum Normal Value')),
                ('unit', models.CharField(blank=True, choices=[('m', 'mg/dL.')], max_length=10, null=True, verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analysis',
            },
            bases=('Service.service',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('servicerecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Service.servicerecord')),
                ('result', models.CharField(verbose_name='Result')),
                ('neg_or_pos', models.CharField(blank=True, choices=[('N', 'Negative'), ('VP', 'Very Weak Positive'), ('WP', 'Weak Positive'), ('P', 'Positive'), ('SP', 'Strong Positive')], max_length=2, null=True, verbose_name='Description(Positive/Negative)')),
                ('description_level', models.CharField(choices=[('L', 'Low'), ('N', 'Normal'), ('H', 'High')], max_length=1, verbose_name='Description Level')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
            bases=('Service.servicerecord',),
        ),
    ]
