# Generated by Django 4.2.7 on 2023-12-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Employee.employee')),
                ('medical_specialty', models.CharField(choices=[('IM', 'Internal Medicine'), ('N', 'Nephrology'), ('NR', 'Neurology '), ('OG', 'Obstetrics & Gynecology')], max_length=2, verbose_name='Medical Specialty')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
            bases=('Employee.employee',),
        ),
    ]
